### ISSUE TITLE
Absent the check that _GLIBCXX_RELEASE is defined

### ISSUE THREAD

**Issue by SergeyKopienko** [oneapi-src/oneDPL#1246]
https://github.com/oneapi-src/oneDPL/blob/8e5334da68f8351db4d4e36aa52506d14584bef0/include/oneapi/dpl/internal/common_config.h#L34

**Comment by kboyarinov** [comment]
As I investigated, it is safe to define `PSTL_USE_PARALLEL_POLICIES` to the expression that uses undefined (yet) macro `_GLIBCXX_RELEASE`. The only important thing is to use `PSTL_USE_PARALLEL_POLICIES` only after `_GLIBCXX_RELEASE` definition. The only place where this macro is used in our repository it this config. And also there is no user impact because it is guaranteed that after including of any oneDPL public headers, `_GLIBCXX_RELEASE` would be defined.
