### ISSUE TITLE
What branch / tag should I install ? 

### ISSUE THREAD

**Issue by andreyryabov** [oneapi-src/oneDPL#154]
Main branch fails to build. 
Why don't you create tags with stable releases as all other projects do?

**Comment by AlexVeprev** [comment]
Hi @andreyryabov,

> Why don't you create tags with stable releases as all other projects do?

Tags will be created. Release is just not ready yet that's why there is no new tags, currently it is stabilized/verified on [release/2021.2](https://github.com/oneapi-src/oneDPL/tree/release/2021.2), tag will be created once stabilization/verification is completed.

> Main branch fails to build.

Could you please provide more details about the failure? Pinging @capatober, @MikeDvorskiy for it.
