### ISSUE TITLE
oneDPL version question

### ISSUE THREAD

**Issue by jinz2014** [oneapi-src/oneDPL#1890]
I wonder if the version of oneDPL could be the same as or close to the version of icpx.  (2022.6 |  2024.2)

**Comment by akukanov** [comment]
The version of oneDPL follows semantic versioning rules (https://semver.org), and is therefore driven by the actual changes being done in a release, rather than alignment with anything.

It is unfortunate that the major version has started from 2021 (instead of just 1) and so resembles year-based versioning - but it is not that.
