### ISSUE TITLE
question about Random Number Engines in oneDPL  and Random Number Engines in oneMKL

### ISSUE THREAD

**Issue by zjin-lcf** [oneapi-src/oneDPL#635]
In oneDPL, the names of the engines are:

https://docs.oneapi.io/versions/latest/onedpl/random.html

In oneMKL, the names of the engines are:
https://www.intel.com/content/www/us/en/develop/documentation/oneapi-mkl-dpcpp-developer-reference/top/random-number-generators/random-number-generators-device-routines/device-engines-basic-random-number-generators.html

Can you please explain the relationships between the engines from the two components   ?  Thanks.

**Comment by aelizaro** [comment]
Hi @zjin-lcf, thank you for the question! There is no direct mapping for oneDPL and oneMKL random number generators, as we aim for different goals for these products:

- in oneDPL our primary goal is to provide templated generators similar to C++ standard ones, which can be used in DPC++ kernels + we have vector extension (sycl::vec instead of the single random number produced per operator() call) to achieve better performance.

- in oneMKL we provide the different set of predefined generators, which may not be part of C++ standard, but they are quite popular (for example philox4x32x10 and mcg31m1/mcg59) and have good quality and performance.

Please let me know if it helps you.

**Comment by zjin-lcf** [comment]
It is not clear that these quite popular ones are not part of C++ standard. 

When people migrate APIs in the CUDA random number library to DPC++, it may be helpful that people just call APIs from only one of the two libraries (oneDPL or oneMKL).

**Comment by aelizaro** [comment]
There were multiple proposals to add these generators to the C++ standard. One of the latest: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2075r1.pdf but it takes quite a long time.

I would disagree because CUDA also has random number generators in cuRAND (set is mostly overlapped with oneMKL functionality) and in Thrust with C++ standard generators mostly.

**Comment by zjin-lcf** [comment]
Okay.  Is it right that people should migrate cuRAND functions with oneMKL functions and migrate Thrust standard generators with oneDPL functions ?

**Comment by aelizaro** [comment]
yes, you are right. For cuRAND APIs oneMKL should be used and in case of Thrust RNGs please use oneDPL.

**Comment by zjin-lcf** [comment]
Thanks.
