### ISSUE TITLE
ONEAPI_DEVICE_SELECTOR inplace of SYCL_DEVICE_FILTER

### ISSUE THREAD

**Issue by abagusetty** [oneapi-src/oneDPL#787]
I was trying to use the compiler version and get into runtime issues with tests since this environment variable is set into the cmake-setup and prevents being over-ridden/unset in a bash environment

```[bash]
1/1 Test #14: sycl_iterator.pass ...............Subprocess aborted***Exception:   0.77 sec

WARNING: The enviroment variable SYCL_DEVICE_FILTER is deprecated. Please use ONEAPI_DEVICE_SELECTOR instead.
For more details, please refer to:
https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md#oneapi_device_selector

terminate called after throwing an instance of 'sycl::_V1::exception'
  what():  ONEAPI_DEVICE_SELECTOR cannot be used in conjunction with SYCL_DEVICE_FILTER
```
Occurances:
```[bash]
./make/Makefile.common:58:        export SYCL_DEVICE_FILTER=$(device_type)
./test/CMakeLists.txt:74:            set(SYCL_DEVICE_FILTER *:acc)
./test/CMakeLists.txt:77:            set(SYCL_DEVICE_FILTER ${ONEDPL_DEVICE_BACKEND}:${ONEDPL_DEVICE_TYPE})
./test/CMakeLists.txt:79:        set_tests_properties(${_test_name} PROPERTIES ENVIRONMENT SYCL_DEVICE_FILTER=${SYCL_DEVICE_FILTER})
```

**Comment by abagusetty** [comment]
Additional Context: I was using the latest compiler built with the hash https://github.com/intel/llvm/commit/1ed2378b6072a0f70c55f4105339b527c7015a75

**Comment by dmitriy-sobolev** [comment]
Hello, @abagusetty. Thanks for highlighting that issue. 

`SYCL_DEVICE_FILTER` variable is deprecated and I am going to replace it with `ONEAPI_DEVICE_SELECTOR` (only for recent releases of `Intel® oneAPI DPC++/C++ Compiler` supporting it). I am investigating how to override an environment variable set via `set_test_properties` after configuring cmake and before running tests.
 
Meanwhile, could you describe your case in more details? What is the value of `ONEAPI_DEVICE_SELECTOR` you set? What is the cmake command you ran?

I am asking because properly selected `ONEDPL_DEVICE_TYPE` and `ONEDPL_DEVICE_TYPE` variables may cover your case:
1. `SYCL_DEVICE_FILTER` has almost the same functionality as `ONEAPI_DEVICE_SELECTOR` 
2. oneDPL cmake sets `SYCL_DEVICE_FILTER` it basing on `ONEDPL_DEVICE_TYPE` and `ONEDPL_DEVICE_TYPE` variables

For example:
```bash
# SYCL_DEVICE_FILTER=level_zero:gpu
cmake -DCMAKE_CXX_COMPILER=dpcpp -DONEDPL_DEVICE_TYPE=GPU -DONEDPL_DEVICE_BACKEND=level_zero /path/to/oneDPL
```
```bash
# SYCL_DEVICE_FILTER=opencl:cpu
cmake -DCMAKE_CXX_COMPILER=dpcpp -DONEDPL_DEVICE_TYPE=CPU -DONEDPL_DEVICE_BACKEND=opencl /path/to/oneDPL
```

**Comment by abagusetty** [comment]
Thanks @dmitriy-sobolev for digging it in for a much stable solution. 

I've tested with just replacing the `SYCL_DEVICE_FILTER` with `ONEAPI_DEVICE_SELECTOR` at the 4 occurance in the CMakeLists.txt to work for L0 backend and that worked fine. Passing the appropriate `DONEDPL_DEVICE_TYPE` and `DONEDPL_DEVICE_BACKEND` took care of the options. 

These were some of the options, I was testing with. The later two for CUDA and HIP backend were mostly experimental. 
```bash
`ONEAPI_DEVICE_SELECTOR=level_zero:gpu` 
`ONEAPI_DEVICE_SELECTOR=ext_oneapi_cuda:gpu` 
`ONEAPI_DEVICE_SELECTOR=ext_oneapi_hip:gpu` 
```

**Comment by abagusetty** [comment]
Also it seems like the `dpcpp` wrapper was be deprecated recently, I was passing `clang++` or `icpx` depending upon whether the compiler was built from source or from a SDK respectively.

**Comment by dmitriy-sobolev** [comment]
@abagusetty, I noticed that [EnvironmentVariables.md](https://github.com/intel/llvm/blob/sycl/sycl/doc/EnvironmentVariables.md) mentions `cuda` and `hip`  instead of `ext_oneapi_cuda` or `ext_oneapi_hip`. I guess you should have used `cuda` or `hip`, but let me know if `ext_oneapi_cuda` or `ext_oneapi_hip` options can be passed as well.

**Comment by abagusetty** [comment]
@dmitriy-sobolev Both worked for me. (i.e., `cuda` or `ext_oneapi_cuda`) similarly for HIP. I was just using the same env variable as being used by the CTS & LLVM CI (i.e., `ext_oneapi_cuda/hip`).

**Comment by dmitriy-sobolev** [comment]
Thanks. Looks like these are synonyms. I prefer leaving only documented names in #803.

**Comment by abagusetty** [comment]
> Thanks. Looks like these are synonyms. I prefer leaving only documented names in #803.

I certainly would agree to that as well.

**Comment by abagusetty** [comment]
Closing.
